# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'giphyApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  platform :ios, '8.0'
  pod 'SDWebImage', '~> 5.0'
  pod 'SDWebImageFLPlugin'

end
